#!/bin/bash

# mount proc, sysfs and devpts in chroot
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts

# set locale variables
export HOME=/root
export LC_ALL=C

# set install settings
dbus-uuidgen > /var/lib/dbus/machine-id
dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl

echo ""
echo Type ./end to end working in the chroot environment.
echo ""